web:
  build: .
  ports:
    - "3000:3000"
  links:
    - db
  environment:
    DB_USERNAME: root
    DB_PASSWORD: root
    DB_HOST: db
    RAILS_ENV: development
db:
  image: library/mysql:5.6.22
  ports:
    - "13306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: root
    DB_USERNAME: root
    DB_PASSWORD: root
